name: Test, build, and release

on:
  push:
    branches:
      - master
      - main

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check formatting
        run: yarn prettier

      - name: Check types
        run: yarn type-check

      - name: Lint
        run: yarn lint

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

  release:
    name: Release

    needs: [test, build]

    runs-on: ubuntu-latest

    steps:
      - name: Preserve line endings
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Semantic Release
        if: success()
        run: HUSKY=0 npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
