name: Test and build

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}

      - name: Check formatting
        run: yarn prettier
        env:
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}

      - name: Check types
        run: yarn type-check
        env:
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}

      - name: Lint
        run: yarn lint
        env:
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}

      - name: Build
        run: yarn build
        env:
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
